### ISSUE TITLE
Relevant changes from upstream for LLVM 18 cycle

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/flang-feedstock#35] opened 2023-11-10 20:46 UTC
No claim of completeness.

Still waiting if the runtime lib refactor relands, ~as well as the switch to HLFIR as a default (looks [close](https://discourse.llvm.org/t/rfc-enabling-the-hlfir-lowering-by-default/72778/7))~ [happened] or finally switching the name of the binary to `flang`.

* https://github.com/llvm/llvm-project/commit/cf1e3420b0141d84770869205cfdb546609014dd (ability to compile against specific MSVC CRT)
* https://github.com/llvm/llvm-project/commit/aa8af04d0c5bffd43500dd635b8d25c7bd191afc (switch to new HLFIR lowering by default)
* https://github.com/llvm/llvm-project/commit/34e4e5eb70818fca90574beb8f5617e27bfac138 (accept `-rpath`)
* https://github.com/llvm/llvm-project/commit/0bc7cd4d51226344a54da5929d87184730e73e83 (enable `--dependent-lib` like clang)
* https://github.com/llvm/llvm-project/commit/caba0314cf631a3ba3e982cbcdc455224046c7a8 (a relevant optimization now on by default)
* https://github.com/llvm/llvm-project/commit/76041a45bbe3cd2b3b3acad46267f27815e6a652 (changes around linkage of runtime libs & `Fortran_main`)
* https://github.com/llvm/llvm-project/commit/9d6837d595719904720e5ff68ec1f1a2665bdc2f (`Fortran_main` not linked by default in `-shared` builds anymore)

**Comment by Krande** [comment] 2024-04-10 08:51
Hey @h-vetinari. By the looks of it, it seems most (if not all) of the referred issued are closed and merged into 18.1? 


Over at the [code-aster-feedstock](https://github.com/conda-forge/code-aster-feedstock) we're looking into adding support for windows. Windows support would require us to enable Fortran support on multiple of our dependencies. I'd be happy to spend some time debugging flang-new issues on our dependencies. For references, here are the dependencies I am looking into

- [hdf5](https://github.com/conda-forge/hdf5-feedstock)
- [mfront](https://github.com/conda-forge/mfront-feedstock)
- [mgis](https://github.com/Krande/mgis-feedstock)
- [libmed](https://github.com/conda-forge/libmed-feedstock)
- [medcoupling](https://github.com/conda-forge/medcoupling-feedstock)
- [mumps](https://github.com/conda-forge/mumps-feedstock) (optional)

In my initial attempts on the `hdf5` and `mfront` packages it seems I am running into some immediate failures (which I'd wager is mostly due to me not using the appropriate flags for flang-new). 

When investigating the state of flang on windows and some of the errors I was seeing, I came across [this error](https://github.com/llvm/llvm-project/issues/86459) reported for the flang=18.1.2 conda-forge package (which I was able to reproduce with flang v18.1.3 on conda-forge and the same error is an issue when compiling `mfront`). I haven't tested compiling flang from source yet though, but I thought that would be the next logical step. 

Any thoughts on the reported "fails to lower FIR" error for flang specifically on conda-forge?

**Comment by h-vetinari** [comment] 2024-04-10 09:19
Hey @Krande, thanks for the comment!

I already commented on the issue you're referencing (which I wasn't aware of - thanks!). Unless we uncover some failure in the packaging (certainly possible, but I'm not aware of anything at the moment), then anything with "lowering to FIR failed" is pretty obviously related to upstream flang to me. For context, FIR is the "Fortran Intermediate Representation" that the compiler uses to go from source code to machine code, and way more low-level than anything we're touching in the packaging.

**Comment by h-vetinari** [comment] 2024-04-10 09:21
> By the looks of it, it seems most (if not all) of the referred issued are closed and merged into 18.1?

PS. Yes, all those commits were merged before 18.x even branched from main, so they're definitely part of the release. I mainly kept a list of relevant changes for myself from occasionally checking out what's happening upstream.

**Comment by h-vetinari** [comment] 2024-07-19 02:08
Closing this as we've published flang 18 a while ago.

**Closed** 2024-08-02 21:27 UTC
